module.exports = {

  ActionTypes: {
    CLICK_THREAD: 'CLICK_THREAD',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    RECEIVE_RAW_CREATED_MESSAGE: 'RECEIVE_RAW_CREATED_MESSAGE',
    RECEIVE_RAW_MESSAGES: 'RECEIVE_RAW_MESSAGES'
  },

  PayloadSources: {
   SERVER_ACTION: 'SERVER_ACTION',
   VIEW_ACTION: 'VIEW_ACTION'
  }
};

