module.exports = {

  Playlist: {
    ADD_PLAYLIST: 'ADD_PLAYLIST',
    UPDATE_PLAYLIST: 'UPDATE_PLAYLIST',
    DELETE_PLAYLIST: 'DELETE_PLAYLIST',
    ADD_PLAYLIST_SONG: 'ADD_PLAYLIST_SONG',
    REMOVE_PLAYLIST_SONG: 'REMOVE_PLAYLIST_SONG'
  },
  PlaylistServer: {
    RECEIVE_ALL_PLAYLISTS: 'RECEIVE_ALL_PLAYLISTS',
    RECEIVE_CREATED_PLAYLISTS: 'RECEIVE_CREATED_PLAYLISTS',
    RECEIVE_UPDATED_PLAYLISTS: 'RECEIVE_UPDATED_PLAYLISTS',
    RECEIVE_CREATED_PLAYLIST_SONGS: 'RECEIVE_CREATED_PLAYLIST_SONGS'
  },
  SongServer: {
    RECEIVE_ALL_SONGS: 'RECEIVE_ALL_SONGS'
  }
};
