module.exports = {

  Playlist: {
    ADD_PLAYLIST: 'ADD_PLAYLIST',
    UPDATE_PLAYLIST: 'UPDATE_PLAYLIST',
    DELETE_PLAYLIST: 'DELETE_PLAYLIST',
    ADD_SONG: 'ADD_SONG',
    REMOVE_SONG: 'REMOVE_SONG'
  }
};
